### ISSUE TITLE
Child components not rendering inside of <Toast> component

### ISSUE THREAD

**Issue by marcusmolchany** [magicismight/react-native-root-toast#90]
I'm using expo, and in development using the expo client app, the <Toast> and children components render properly. However, once I deploy to a standalone app, the children are no longer rendering.

this is what my render method looks like:
```js
render() {
  return (
    <Toast
        animation
        backgroundColor={TOAST_BACKGROUND_COLOR}
        containerStyle={styles.container}
        hideOnPress
        textColor={TOAST_TEXT_COLOR}
        onHide={this.onHide}
        opacity={0.98}
        position={50}
        shadow={false}
        visible={isVisible}
    >
       <View>
         <Text>Hello</Text>
       </View>
    </Toast>
  );
}
```

**Comment by sunnylqm** [comment]
Toast is designed for [text message only](https://github.com/magicismight/react-native-root-toast/blob/master/lib/ToastContainer.js#L247-L253). But [on iOS you can nest view in text](https://facebook.github.io/react-native/docs/text#nested-views-ios-only) so that's why sometimes your code works but sometimes not. You should use https://github.com/magicismight/react-native-root-modal or https://github.com/magicismight/react-native-root-siblings If you want child components.

**Comment by marcusmolchany** [comment]
awesome thanks!
